# Used for combining the ensemble tool scores

# Introme AG/GT Computation (computed during Introme)
[[annotation]]
file = "introme_annotate.ag_check.vcf.gz"
fields = ["variant_type", "ag_created", "ag_lost", "gt_created", "gt_lost"]
ops = ["uniq","uniq","uniq", "uniq", "uniq"]
names = ["Variant_Type", "AG_Created", "AG_Lost", "GT_Created", "GT_Lost"]

# ESE Scoring (computed during Introme)
[[annotation]]
# file = "introme_annotate.ESE.vcf.gz"
file = "introme_annotate.ESE.tsv.gz"
columns = [9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]
# names =  ["A1_Hazeem_alt"]
# ops = ["self"]
# columns = [3]
# fields =  ["A1_Hazeem_alt", "A1_Hazeem_diff", "A1_Hazeem_july_alt", "A1_Hazeem_july_diff", "A1_neuBG_alt", "A1_neuBG_diff", "A1_winBG_alt", "A1_winBG_diff", "SRSF1_alt", "SRSF1_diff", "SRSF1_igM_alt", "SRSF1_igM_diff", "SRSF2_alt", "SRSF2_diff", "SRSF5_alt", "SRSF5_diff", "SRSF6_alt", "SRSF6_diff"]
ops = ["self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self"]
names =  ["ESE_A1_Hazeem_alt", "ESE_A1_Hazeem_diff", "ESE_A1_Hazeem_july_alt", "ESE_A1_Hazeem_july_diff", "ESE_A1_neuBG_alt", "ESE_A1_neuBG_diff", "ESE_A1_winBG_alt", "ESE_A1_winBG_diff", "ESE_SRSF1_alt", "ESE_SRSF1_diff", "ESE_SRSF1_igM_alt", "ESE_SRSF1_igM_diff", "ESE_SRSF2_alt", "ESE_SRSF2_diff", "ESE_SRSF5_alt", "ESE_SRSF5_diff", "ESE_SRSF6_alt", "ESE_SRSF6_diff"]

# SpliceAI Annotations
#SpliceAI VCF Processing
[[annotation]]
file = "spliceai.vcf.gz"
fields = ["SpliceAI"]
names = ["SpliceAI_raw"]
ops = ["self"]

#SpliceAI VCF Processing
[[postannotation]]
fields = ["SpliceAI_raw"]
op = "lua:spliceai(SpliceAI_raw)"
type = "String"
name = "SpliceAI_processed"

# ##INFO=<ID=SpliceAI,Number=.,Type=String,Description="SpliceAIv1.3.1 variant annotation.
# These include delta scores (DS) and delta positions (DP) for acceptor gain (AG), acceptor loss (AL), donor gain (DG), donor loss (DL),
# acceptor gain reference score (DS_AG_REF), acceptor gain variant score (DS_AG_ALT),
# acceptor loss reference score (DS_AL_REF), acceptor loss variant score (DS_AL_ALT),
# donor gain reference score (DS_DG_REF), donor gain variant score (DS_DG_ALT),
# donor loss reference score (DS_DL_REF), donor loss variant score (DS_DL_ALT)
#
# Format: ALLELE|NAME|STRAND|DS_AG|DS_AL|DS_DG|DS_DL|DP_AG|DP_AL|DP_DG|DP_DL|
#          1    | 2  | 3    | 4   | 5   | 6   | 7   | 8   | 9   | 10  | 11  |
# DS_AG_REF|DS_AG_ALT|DS_AL_REF|DS_AL_ALT|DS_DG_REF|DS_DG_ALT|DS_DL_REF|DS_DL_ALT">
#  12      | 13      | 14      | 15      | 16      | 17      | 18      | 19

# TODO: seems really wasteful to have to split anew for every score
# - why not compute everything into a table once and access by index?

# SpliceAI DS_AG
[[postannotation]]
fields = ["SpliceAI_processed"]
op = "lua:split(SpliceAI_processed,'|')[4]"
type = "Float"
name = "DS_AG"

# SpliceAI DS_AL
[[postannotation]]
fields = ["SpliceAI_processed"]
op = "lua:split(SpliceAI_processed,'|')[5]"
type = "Float"
name = "DS_AL"

# SpliceAI DS_DG
[[postannotation]]
fields = ["SpliceAI_processed"]
op = "lua:split(SpliceAI_processed,'|')[6]"
type = "Float"
name = "DS_DG"

# SpliceAI DS_DL
[[postannotation]]
fields = ["SpliceAI_processed"]
op = "lua:split(SpliceAI_processed,'|')[7]"
type = "Float"
name = "DS_DL"

# SpliceAI DP_AG
[[postannotation]]
fields = ["SpliceAI_processed"]
op = "lua:split(SpliceAI_processed,'|')[8]"
type = "Float"
name = "DP_AG"

# SpliceAI DP_AL
[[postannotation]]
fields = ["SpliceAI_processed"]
op = "lua:split(SpliceAI_processed,'|')[9]"
type = "Float"
name = "DP_AL"

# SpliceAI DP_DG
[[postannotation]]
fields = ["SpliceAI_processed"]
op = "lua:split(SpliceAI_processed,'|')[10]"
type = "Float"
name = "DP_DG"

# SpliceAI DP_DL
[[postannotation]]
fields = ["SpliceAI_processed"]
op = "lua:split(SpliceAI_processed,'|')[11]"
type = "Float"
name = "DP_DL"

# SpliceAI DS_AG_ALT
[[postannotation]]
fields = ["SpliceAI_processed"]
op = "lua:split(SpliceAI_processed,'|')[13]"
type = "Float"
name = "DS_AG_ALT"

# SpliceAI DS_AL_ALT
[[postannotation]]
fields = ["SpliceAI_processed"]
op = "lua:split(SpliceAI_processed,'|')[15]"
type = "Float"
name = "DS_AL_ALT"

# SpliceAI DS_DG_ALT
[[postannotation]]
fields = ["SpliceAI_processed"]
op = "lua:split(SpliceAI_processed,'|')[17]"
type = "Float"
name = "DS_DG_ALT"

# SpliceAI DS_DL_ALT
[[postannotation]]
fields = ["SpliceAI_processed"]
op = "lua:split(SpliceAI_processed,'|')[19]"
type = "Float"
name = "DS_DL_ALT"

# SpliceAI delete
[[postannotation]]
fields = ["SpliceAI_processed", "SpliceAI_raw"]
op = "delete"


# MMSplice (computed during Introme)
##INFO=<ID=CSQ,Number=.,Type=String,Description="mmsplice splice variant effect.
# Format: mmsplice_alt_acceptor|mmsplice_alt_acceptorIntron|
#          1                   | 2                         |
#         mmsplice_alt_donor|mmsplice_alt_donorIntron|mmsplice_alt_exon|
#          3                | 4                      | 5               |
#         mmsplice_delta_logit_psi|mmsplice_pathogenicity|
#          6                      | 7                    |
#         mmsplice_ref_acceptor|mmsplice_ref_acceptorIntron|
#          8                   | 9                         |
#         mmsplice_ref_donor|mmsplice_ref_donorIntron|mmsplice_ref_exon">
#          10               | 11                     | 12

[[annotation]]
file = "mmsplice.vcf.gz"
fields = ["CSQ"]
ops = ["self"]
names = ["MMSplice_raw"]

[[postannotation]]
fields = ["MMSplice_raw"]
op = "lua:mmsplice(MMSplice_raw)"
type = "String"
name = "MMSplice_processed"

[[postannotation]]
fields = ["MMSplice_processed"]
op = "lua:split(MMSplice_processed,'|')[1]"
type = "Float"
name = "MMSplice_alt_acceptor"

[[postannotation]]
fields = ["MMSplice_processed"]
op = "lua:split(MMSplice_processed,'|')[2]"
type = "Float"
name = "MMSplice_alt_acceptor_intron"

[[postannotation]]
fields = ["MMSplice_processed"]
op = "lua:split(MMSplice_processed,'|')[3]"
type = "Float"
name = "MMSplice_alt_donor"

[[postannotation]]
fields = ["MMSplice_processed"]
op = "lua:split(MMSplice_processed,'|')[4]"
type = "Float"
name = "MMSplice_alt_donor_intron"

[[postannotation]]
fields = ["MMSplice_processed"]
op = "lua:split(MMSplice_processed,'|')[5]"
type = "Float"
name = "MMSplice_alt_exon"

[[postannotation]]
fields = ["MMSplice_processed"]
op = "lua:split(MMSplice_processed,'|')[6]"
type = "Float"
name = "MMSplice_delta_logit_PSI"

[[postannotation]]
fields = ["MMSplice_processed"]
op = "lua:split(MMSplice_processed,'|')[7]"
type = "Float"
name = "MMSplice_pathogenicity"

[[postannotation]]
fields = ["MMSplice_processed"]
op = "lua:split(MMSplice_processed,'|')[8]"
type = "Float"
name = "MMSplice_ref_acceptor"

[[postannotation]]
fields = ["MMSplice_processed"]
op = "lua:split(MMSplice_processed,'|')[9]"
type = "Float"
name = "MMSplice_ref_acceptor_intron"

[[postannotation]]
fields = ["MMSplice_processed"]
op = "lua:split(MMSplice_processed,'|')[10]"
type = "Float"
name = "MMSplice_ref_donor"

[[postannotation]]
fields = ["MMSplice_processed"]
op = "lua:split(MMSplice_processed,'|')[11]"
type = "Float"
name = "MMSplice_ref_donor_intron"

[[postannotation]]
fields = ["MMSplice_processed"]
op = "lua:split(MMSplice_processed,'|')[12]"
type = "Float"
name = "MMSplice_ref_exon"

# MMSplice delete
[[postannotation]]
fields = ["MMSplice_raw", "MMSplice_processed"]
op = "delete"

# Pangolin Annotations
# Pangolin VCF Processing
[[annotation]]
file = "pangolin.vcf.gz"
fields = ["Pangolin"]
names = ["Pangolin_raw"]
ops = ["self"]

# Pangolin VCF Processing
[[postannotation]]
fields = ["Pangolin_raw"]
op = "lua:pangolin(Pangolin_raw)"
type = "String"
name = "Pangolin_processed"

# Pangolin gain
[[postannotation]]
fields = ["Pangolin_processed"]
op = "lua:split(split(Pangolin_processed,'|')[2], ':')[2]"
type = "Float"
name = "Pangolin_Gain"

# Pangolin loss
[[postannotation]]
fields = ["Pangolin_processed"]
op = "lua:split(split(Pangolin_processed,'|')[3], ':')[2]"
type = "Float"
name = "Pangolin_Loss"

# Pangolin delete
[[postannotation]]
fields = ["Pangolin_processed", "Pangolin_raw"]
op = "delete"

# SPIP Annotations
# SPIP VCF Processing
##INFO=<ID=SPiP,Number=.,Type=String,Description="SPiPs predictions of splicing defects.
# Format: 'Alt|varID|Interpretation|InterConfident|SPiPscore|strand|gNomen|varType|ntChange|
#           1 | 2   | 3            | 4            | 5       | 6    | 7    | 8     | 9      |
# ExonInfo|exonSize|transcript|gene|NearestSS|DistSS|RegType|SPiCEproba|SPiCEinter_2thr|
#  10     | 11     | 12       | 13 | 14      | 15   | 16    | 17       | 18            |
# deltaMES|BP|mutInPBarea|deltaESRscore|posCryptMut|sstypeCryptMut|probaCryptMut|
# classProbaCryptMut|nearestSStoCrypt|nearestPosSStoCrypt|nearestDistSStoCrypt|posCryptWT|
# probaCryptWT|classProbaCryptWT|posSSPhysio|probaSSPhysio|classProbaSSPhysio|probaSSPhysioMut|
# classProbaSSPhysioMut'">

[[annotation]]
file = "spip.vcf.gz"
fields = ["SPiP"]
names = ["SPiP_raw"]
ops = ["self"]

# SPIP VCF Processing
[[postannotation]]
fields = ["SPiP_raw"]
op = "lua:spip(SPiP_raw)"
type = "String"
name = "SPiP_processed"

# SPIP Interconfident score
[[postannotation]]
fields = ["SPiP_processed"]
op = "lua:spip_interconfident(SPiP_processed)"
type = "Float"
name = "SPIP_Score"

# SPIP Interconfident min range
[[postannotation]]
fields = ["SPiP_processed"]
op = "lua:spip_min(SPiP_processed)"
type = "Float"
name = "SPIP_Range_Min"

# SPIP Interconfident min range
[[postannotation]]
fields = ["SPiP_processed"]
op = "lua:spip_max(SPiP_processed)"
type = "Float"
name = "SPIP_Range_Max"

# SPIP SPiCE Probability score
[[postannotation]]
fields = ["SPiP_processed"]
op = "lua:split(SPiP_processed,'|')[17]"
type = "Float"
name = "SPiCE_Prob"

# SPIP delete
[[postannotation]]
fields = ["SPiP_processed", "SPiP_raw"]
op = "delete"

# Spliceogen Annotations
# CHR	START	END	REF	ALT	GENE	withinSite	mesDonRef	mesDonAlt	mesAccRef	mesAccAlt	gsDonRef
#  1     2       3   4   5   6       7           8           9           10          11          12
# gsDonAlt	gsAccRef	gsAccAlt	ESEmaxRef	ESEmaxAlt	ESSminRef	ESSminAlt	donGainP	accGainP	donLossP	accLossP
#  13        14          15          16          17          18          19          20          21          22          23

[[annotation]]
file = "spliceogen.tsv.gz"
columns = [8, 9, 10, 11,
            16, 17, 18, 19,
            20, 21, 22, 23]
names = ["mesDonRef", "mesDonAlt", "mesAccRef", "mesAccAlt",
    "ESEmaxRef", "ESEmaxAlt", "ESSminRef", "ESSminAlt",
    "DonGainP", "AccGainP", "DonLossP", "AccLossP"]
ops = ["self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self"]


# # Squirl Annotations
# # Squirl VCF Processing
# [[annotation]]
# file = "squirl.vcf.gz"
# fields = ["SQUIRLS_SCORE"]
# names = ["Squirl_processed"]
# ops = ["self"]


# names = ["MMSplice_alt_acceptor", "MMSplice_alt_acceptor_intron", "MMSplice_alt_donor", "MMSplice_alt_donor_intron", "MMSplice_alt_exon", "MMSplice_delta_logit_PSI", "MMSplice_pathogenicity", "MMSplice_ref_acceptor", "MMSplice_ref_acceptor_intron", "MMSplice_ref_donor", "MMSplice_ref_donor_intron", "MMSplice_ref_exon"]