# File used by VCFanno to define how a VCF file should be annotated
# File for splicing score annotation (computed during introme)

[[annotation]]
file="introme_annotate.spliceai.vcf.gz"
fields = ["gene", "DS_AG", "DS_AL", "DS_DG", "DS_DL", "DP_AG", "DP_AL", "DP_DG", "DP_DL"]
ops=["self", "self", "self", "self", "self", "self", "self", "self", "self"]
names=["SpliceAI_Gene", "SpliceAI_Acceptor_Gain", "SpliceAI_Acceptor_Loss", "SpliceAI_Donor_Gain", "SpliceAI_Donor_Loss",  "SpliceAI_DP_Acceptor_Gain", "SpliceAI_DP_Acceptor_Loss", "SpliceAI_DP_Donor_Gain", "SpliceAI_DP_Donor_Loss"]

[[annotation]]
file="introme_annotate.mmsplice.vcf.gz"
fields = ["alt_acceptor", "alt_acceptor_intron", "alt_donor", "alt_donor_intron", "alt_exon", "delta_logit_PSI", "pathogenicity", "ref_acceptor", "ref_acceptor_intron", "ref_donor", "ref_donor_intron", "ref_exon"]
ops=["self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self", "self"]
names=["MMSplice_alt_acceptor", "MMSplice_alt_acceptor_intron", "MMSplice_alt_donor", "MMSplice_alt_donor_intron", "MMSplice_alt_exon", "MMSplice_delta_logit_PSI", "MMSplice_pathogenicity", "MMSplice_ref_acceptor", "MMSplice_ref_acceptor_intron", "MMSplice_ref_donor", "MMSplice_ref_donor_intron", "MMSplice_ref_exon"]

[[annotation]]
file="introme_annotate.functions.vcf.gz"
fields = ["variant_type", "ag_created", "ag_lost", "gt_created", "gt_lost"]
ops=["self","self","self","self","self"]
names=["Variant_Type", "AG_Created", "AG_Lost", "GT_Created", "GT_Lost"]

[[annotation]]
file="introme_annotate.spliceogen.vcf.gz"
fields = ["mesDonRef", "mesDonAlt", "mesAccRef", "mesAccAlt", "ESEmaxRef", "ESEmaxAlt", "ESEminRef", "ESEminAlt", "DonGainP", "AccGainP", "DonLossP", "AccLossP"]
ops=["self","self","self","self","self","self","self","self","self","self","self","self"]
names=["mesDonRef", "mesDonAlt", "mesAccRef", "mesAccAlt", "ESEmaxRef", "ESEmaxAlt", "ESEminRef", "ESEminAlt", "DonGainP", "AccGainP", "DonLossP", "AccLossP"]
