# File used by VCFanno to define how a VCF file should be annotated
# File for allele frequency annotation using wdl

[[annotation]]
file="gnomad.genomes.sites.merged.AF_AC_AN_only.vcf.gz"
fields = ["AF_POPMAX"]
ops=["self"]
names=["gnomAD_PM_AF"]

[[annotation]]
file="reheadered.MGRB.vcf.gz"
fields=["AF"]
ops=["self"]
names=["MGRB_AF"]

[[annotation]]
file="regions.bed.gz"
columns = [6]
ops=["self"]
names=["Gene_Regions"]
